const { env } = require('../config/env');

function detectIntent(question) {
  const q = String(question || '').toLowerCase();
  if (q.includes('biggest weakness') || q.includes('main weakness')) return 'weakness-diagnosis';
  if (q.includes('4-week') || q.includes('4 week') || q.includes('week')) return 'four-week-plan';
  if (q.includes('weight') || q.includes('cut')) return 'weight-cut-plan';
  if (q.includes('fight') || q.includes('bout')) return 'fight-prep';
  return 'general-coaching';
}

function isIntentSatisfied(result, intent) {
  const summary = String(result?.summary || '').toLowerCase();
  const weeks = Array.isArray(result?.focus_next_4_weeks) ? result.focus_next_4_weeks : [];

  if (intent === 'four-week-plan') {
    const hasWeekProgression = weeks.length === 4 && weeks.every((w) => /week\s*-?\s*[1-4]/i.test(String(w || '')));
    const hasPlanLanguage = summary.includes('4-week') || summary.includes('4 week') || summary.includes('plan');
    const notWeaknessOnly = !summary.includes('biggest weakness');
    return hasWeekProgression && hasPlanLanguage && notWeaknessOnly;
  }

  if (intent === 'weakness-diagnosis') {
    return summary.includes('weakness');
  }

  if (intent === 'weight-cut-plan') {
    const blob = `${summary} ${weeks.join(' ')}`.toLowerCase();
    return blob.includes('weight') || blob.includes('hydration') || blob.includes('nutrition');
  }

  if (intent === 'fight-prep') {
    const blob = `${summary} ${weeks.join(' ')}`.toLowerCase();
    return blob.includes('fight') || blob.includes('tactical') || blob.includes('sparring');
  }

  return true;
}

function buildPrompt({ cardio, striking, grappling, discipline, goals, question }) {
  const intent = detectIntent(question);
  const goalSummary = (goals || [])
    .slice(0, 5)
    .map((g, index) => `${index + 1}. ${g.goal_type || g.type || 'goal'} | target=${g.target_value} | current=${g.current_value}`)
    .join('\n');

  return `You are an elite, no-nonsense MMA head coach. Your job is to give direct, high-impact advice based on data.

Fighter Performance Data:
- Cardio: ${cardio}/10
- Striking: ${striking}/10
- Grappling: ${grappling}/10
- Discipline: ${discipline}% (Attendance/Consistency)

Active Goals:
${goalSummary || '- None at the moment.'}

Coach's Query:
"${question || 'Analyze my current state and give me my next mission.'}"

Detected Intent: ${intent}

Return ONLY valid JSON in this exact shape:
{
  "summary": "string (A direct, high-impact assessment. Max 2-3 sentences. No fluff.)",
  "strengths": ["string (2 concise bullets)"],
  "weaknesses": ["string (2 concise bullets)"],
  "recommendations": ["string (2 clear action items)"],
  "focus_next_4_weeks": ["string (4 weekly steps, e.g., 'W1: Focus on X')"]
}

Rules:
- Be extremely brief but accurate. 
- Talk like a real coach (direct, encouraging but firm).
- Address the Coach's Query directly in the summary.
- NO redundancy between fields.
- NO markdown.`;
}

function safeText(value, fallback) {
  const text = String(value || '').trim();
  return text || fallback;
}

function sanitizeList(items, fallback) {
  if (!Array.isArray(items)) return fallback;
  const clean = items
    .map((item) => String(item || '').trim())
    .filter(Boolean)
    .slice(0, 6);
  return clean.length ? clean : fallback;
}

function parseSectionList(text, section) {
  const pattern = new RegExp(`${section}\\s*:?\\s*(?:\\n|$)([\\s\\S]*?)(?:\\n\\s*[A-Za-z][A-Za-z\\s]{2,30}:|$)`, 'i');
  const match = String(text || '').match(pattern);
  if (!match) return [];

  return match[1]
    .split('\n')
    .map((line) => line.replace(/^\s*[-*\d.)\s]+/, '').trim())
    .filter(Boolean)
    .slice(0, 6);
}

function normalizeCoachResult(resultText, payload) {
  const text = String(resultText || '').trim();
  if (!text) {
    return fallbackCoachSummary(payload);
  }

  let parsed = null;
  const fenced = text.match(/\{[\s\S]*\}/);
  const jsonCandidate = fenced ? fenced[0] : text;
  try {
    parsed = JSON.parse(jsonCandidate);
  } catch (error) {
    parsed = null;
  }

  if (parsed && typeof parsed === 'object') {
    const strengths = sanitizeList(parsed.strengths, ['Balanced profile with room for incremental gains.']);
    const weaknesses = sanitizeList(parsed.weaknesses, ['No major red flags detected from current data.']);
    const recommendations = sanitizeList(parsed.recommendations, ['Keep current training balance and progressively increase intensity.']);
    const focus = sanitizeList(parsed.focus_next_4_weeks, recommendations.slice(0, 4));

    return {
      source: 'groq',
      source_detail: 'Generated by Groq model.',
      summary: safeText(parsed.summary, [
        'Strengths:',
        ...strengths.map((item) => `- ${item}`),
        '',
        'Weaknesses:',
        ...weaknesses.map((item) => `- ${item}`),
      ].join('\n')),
      strengths,
      weaknesses,
      recommendations,
      focus_next_4_weeks: focus,
    };
  }

  const strengths = parseSectionList(text, 'Strengths');
  const weaknesses = parseSectionList(text, 'Weaknesses');
  const recommendations = parseSectionList(text, 'Recommendations');

  return {
    source: 'groq',
    source_detail: 'Generated by Groq model (normalized text response).',
    summary: text,
    strengths: strengths.length ? strengths : ['Balanced profile with room for incremental gains.'],
    weaknesses: weaknesses.length ? weaknesses : ['No major red flags detected from current data.'],
    recommendations: recommendations.length ? recommendations : ['Keep current training balance and progressively increase intensity.'],
    focus_next_4_weeks: recommendations.slice(0, 4),
  };
}

function questionAwareFallbackRecommendations(question, defaults) {
  const q = String(question || '').toLowerCase();
  if (!q) return defaults;

  if (q.includes('grappl')) {
    return [
      'Run three focused grappling sessions weekly (takedown defense, guard retention, get-ups).',
      'Add one positional sparring block each session from disadvantaged ground positions.',
      'Track successful takedown defense percentage weekly and target +10% in 4 weeks.',
      'Shift one striking round per session into mat time until grappling score improves.',
    ];
  }

  if (q.includes('weight') || q.includes('cut')) {
    return [
      'Set a controlled weekly weight-loss target and review trends daily.',
      'Use a fixed nutrition template with hydration checkpoints.',
      'Keep one low-impact conditioning day to protect recovery while cutting.',
      'Do a 7-day pre-fight weight rehearsal with sodium and sleep control.',
    ];
  }

  if (q.includes('fight') || q.includes('bout')) {
    return [
      'Prioritize game-plan drilling around your highest-percentage entries.',
      'Run two opponent-style situational rounds weekly.',
      'Add one tactical review session for corner cues and adjustments.',
      'Taper volume in the final week while maintaining reaction speed.',
    ];
  }

  return defaults;
}

function fallbackCoachSummary({ cardio, striking, grappling, discipline, question }) {
  const strengths = [];
  const weaknesses = [];
  const recommendations = [];

  if (cardio >= 8) strengths.push('Strong cardio foundation.');
  if (striking >= 8) strengths.push('Reliable striking performance.');
  if (grappling >= 8) strengths.push('Solid grappling capability.');
  if (discipline >= 80) strengths.push('Excellent attendance and consistency.');

  if (cardio <= 4) {
    weaknesses.push('Cardio is below competitive level.');
    recommendations.push('Add interval conditioning twice weekly.');
  }

  if (grappling <= 4) {
    weaknesses.push('Grappling is a key vulnerability.');
    recommendations.push('Prioritize takedown defense and guard retention drills.');
  }

  if (discipline < 60) {
    weaknesses.push('Attendance discipline is inconsistent.');
    recommendations.push('Set a minimum weekly attendance target and monitor weekly.');
  }

  if (!recommendations.length) {
    recommendations.push('Keep current training balance and progressively increase intensity.');
  }

  const tunedRecommendations = questionAwareFallbackRecommendations(question, recommendations);

  return {
    source: 'fallback',
    source_detail: 'Using local deterministic coaching logic because Groq response was unavailable.',
    strengths: strengths.length ? strengths : ['Balanced profile with room for incremental gains.'],
    weaknesses: weaknesses.length ? weaknesses : ['No major red flags detected from current data.'],
    recommendations: tunedRecommendations,
    focus_next_4_weeks: tunedRecommendations.slice(0, 4),
    summary: [
      'Strengths:',
      ...(strengths.length ? strengths.map((item) => `- ${item}`) : ['- Balanced profile with room for incremental gains.']),
      '',
      'Weaknesses:',
      ...(weaknesses.length ? weaknesses.map((item) => `- ${item}`) : ['- No major red flags detected from current data.']),
      '',
      'Recommendations:',
      ...tunedRecommendations.map((item) => `- ${item}`),
    ].join('\n'),
  };
}

async function getGroqCoachSummary(payload) {
  if (!env.GROQ_API_KEY) {
    throw new Error('GROQ_API_KEY is missing. Set it in backend/.env.');
  }

  const prompt = buildPrompt(payload);
  const intent = detectIntent(payload?.question || '');

  const callGroq = async (userPrompt, correctionNote = '') => {
    const finalUserPrompt = correctionNote
      ? `${userPrompt}\n\nCorrection note:\n${correctionNote}`
      : userPrompt;

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${env.GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: env.GROQ_MODEL,
        messages: [
          { role: 'system', content: 'You are a practical MMA performance coach that returns strict JSON output when asked.' },
          { role: 'user', content: finalUserPrompt },
        ],
        temperature: 0.8,
        top_p: 0.95,
        response_format: { type: 'json_object' },
      }),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`Groq API error (${response.status}): ${errorBody.slice(0, 240)}`);
    }

    const data = await response.json();
    const content = data?.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error('Groq response did not include message content.');
    }

    return normalizeCoachResult(content, payload);
  };

  try {
    const firstPass = await callGroq(prompt);
    if (isIntentSatisfied(firstPass, intent)) {
      return firstPass;
    }

    const secondPass = await callGroq(
      prompt,
      `Your previous answer did not satisfy intent '${intent}'. Rewrite to satisfy that exact intent. For four-week-plan intent, summary must describe a progressive 4-week plan (not biggest weakness framing) and focus_next_4_weeks must be week-by-week progression.`
    );

    return secondPass;
  } catch (error) {
    throw error;
  }
}

module.exports = {
  getGroqCoachSummary,
  fallbackCoachSummary,
};
